<Project Sdk="Microsoft.NET.Sdk">

  
  
  
  
  
  
  <PropertyGroup>
    
    <PackageId>Aero.Services</PackageId>

    
    <Version>0.0.9.1-alpha</Version>

    
    <Authors>Microbians</Authors>

    
    <Description>A lightweight library for making it easier to build .net applications</Description>

    
    <PackageTags>aero;utils;netcore</PackageTags>
    <PackageProjectUrl>https://github.com/microbian-systems/aero</PackageProjectUrl>
    <RepositoryUrl>https://github.com/microbian-systems/aero</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>aero-logo-new.png</PackageIcon>

  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="IdentityService.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="IdentityService.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentEmail.Core" />
    <PackageReference Include="FluentEmail.MailKit" />
    <PackageReference Include="FluentEmail.Mailtrap" />
    <PackageReference Include="FluentEmail.Razor" />
    <PackageReference Include="FluentEmail.SendGrid" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="PasswordGenerator" />
    <PackageReference Include="starkbank-ecdsa" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Twilio.AspNet.Common" />
    <PackageReference Include="Twilio.AspNet.Core" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aero.Caching\Aero.Caching.csproj" />
    <ProjectReference Include="..\Aero.Core\Aero.Core.csproj" />
    <ProjectReference Include="..\Aero.Marten\Aero.Marten.csproj" />
  </ItemGroup>


  <ItemGroup>
    <None Include="..\..\assets\aero-logo-new.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
