<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Alba" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Aero.Models\Aero.Models.csproj" />
    <ProjectReference Include="..\..\src\Aero.MartenDB\Aero.MartenDB.csproj" />
  </ItemGroup>
</Project>
