<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Aero.Secrets</PackageId>
    <Version>0.0.9.1-alpha</Version>
    <Authors>Microbians</Authors>
    <Title>Secrets management for the Aero Web Platform</Title>
    <Description>Secrets management and secure storage for the Aero platform</Description>
    <PackageTags>aero;secrets;security</PackageTags>
    <PackageProjectUrl>https://github.com/microbian-systems/aero</PackageProjectUrl>
    <RepositoryUrl>https://github.com/microbian-systems/aero</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>aero-logo-new.png</PackageIcon>
    <IsPackable>true</IsPackable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Infisical.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aero.Core\Aero.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\assets\aero-logo-new.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
