<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="FakeItEasy.Analyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup></ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Aero.Auth\Aero.Auth.csproj" />
    <ProjectReference Include="..\..\src\Aero.Core\Aero.Core.csproj" />
    <ProjectReference Include="..\..\src\Aero.Models\Aero.Models.csproj" />
    <ProjectReference Include="..\..\src\Aero.Marten\Aero.Marten.csproj" />
    <ProjectReference Include="..\Aero.Auth.Tests.WebHost\Aero.Auth.Tests.WebHost.csproj" />
  </ItemGroup>
  <ItemGroup></ItemGroup>
</Project>
