<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Aero.Core.Ai</PackageId>
    <Version>0.0.9.1-alpha</Version>
    <Authors>Microbians</Authors>
    <Title>AI services for the Aero Web Platform</Title>
    <Description>AI and LLM integration components for the Aero platform</Description>
    <PackageTags>aero;ai;llm</PackageTags>
    <PackageProjectUrl>https://github.com/microbian-systems/aero</PackageProjectUrl>
    <RepositoryUrl>https://github.com/microbian-systems/aero</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>aero-logo-new.png</PackageIcon>
    <IsPackable>true</IsPackable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Aero.Core\Aero.Core.csproj" />
      <ProjectReference Include="..\Aero.Events\Aero.Events.csproj" />
      <ProjectReference Include="..\Aero.Marten\Aero.Marten.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="LlmTornado" />
      <PackageReference Include="LlmTornado.Agents" />
      <PackageReference Include="LlmTornado.Contrib" />
      <PackageReference Include="LlmTornado.Mcp" />
      <PackageReference Include="LlmTornado.Microsoft.Extensions.AI" />
      <PackageReference Include="LlmTornado.Toolkit" />
      <PackageReference Include="LlmTornado.VectorDatabases" />
      <PackageReference Include="LlmTornado.VectorDatabases.PgVector" />
      <PackageReference Include="Microsoft.Agents.AI" />
    </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\aero-logo-new.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
