<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="Bogus" />
    <PackageReference Include="FakeItEasy" />
    <PackageReference Include="Humanizer.Core" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Aero.Social\Aero.Social.csproj" />
    <ProjectReference Include="..\..\src\Aero.Social\Twitter.Client\Aero.Social.Twitter.Client.csproj" />
  </ItemGroup>
</Project>
