<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Marten" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Aero.Cms.Abstractions\Aero.Cms.Abstractions.csproj" />
    <ProjectReference Include="..\Aero.Core\Aero.Core.csproj" />
  </ItemGroup>
</Project>
