<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Aero.Actors</PackageId>
    <Version>0.0.6-alpha</Version>
    <Authors>Microbians</Authors>
    <Title>Core Package for the Aero Web Platform</Title>
    <Description>Core components for the Aero web application platform</Description>
    <Copyright>Microbian Systems 2021</Copyright>
    <PackageProjectUrl>https://github.com/microbian-systems/aero</PackageProjectUrl>
    <RepositoryUrl>https://github.com/microbian-systems/aero</RepositoryUrl>
    <PackageTags>Aero, web, asp.net core, .net, Aero</PackageTags>
    <PackageIcon>aero-logo-new.png</PackageIcon>
    <IsPackable>true</IsPackable>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Core" />
    <PackageReference Include="Microsoft.Orleans.Core.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Aero.Actors.Abstractions\Aero.Actors.Abstractions.csproj" />
    <ProjectReference Include="..\Aero.Core\Aero.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\assets\aero-logo-new.png" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
