<Project>
    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
        <LangVersion>default</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>true</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591;</NoWarn>
    </PropertyGroup>

    <PropertyGroup Label="Package information">
        <VersionPrefix>0.0.6</VersionPrefix>
        <VersionSuffix>alpha</VersionSuffix>
        <Authors>Troy Robinson, et al</Authors>
        <Company>Microbians</Company>
        <Copyright>Copyright (c) 2023-2026 Microbians</Copyright>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PackageTags>asp.net efcore Aero</PackageTags>
        <PackageIcon>aero-logo-new.png</PackageIcon>
        <PackageProjectUrl>https://github.com/microbian-systems/Aero</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/microbian-systems/Aero</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)../assets/aero-logo-new.png" Pack="true" PackagePath="\" />
        <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>