<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MimeKit" />
      <PackageReference Include="System.Data.SqlClient" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Aero.Auth\Aero.Auth.csproj" />
      <ProjectReference Include="..\..\src\Aero.Models\Aero.Models.csproj" />
      <ProjectReference Include="..\..\src\Aero.Web\Aero.Web.csproj" />
    </ItemGroup>

</Project>
